// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUOs7vCJng2kFSyq5A58sdmFjLu69jg6s',
    appId: '1:749924368093:web:8895d26f7fafd47d68a534',
    messagingSenderId: '749924368093',
    projectId: 'almalek-alameen-e205c',
    authDomain: 'almalek-alameen-e205c.firebaseapp.com',
    storageBucket: 'almalek-alameen-e205c.firebasestorage.app',
    measurementId: 'G-171KVVEQBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVCYM2-nxytxrNgVSiSlMLsTutrwHkHKM',
    appId: '1:749924368093:android:71cfc416fc92059a68a534',
    messagingSenderId: '749924368093',
    projectId: 'almalek-alameen-e205c',
    storageBucket: 'almalek-alameen-e205c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb_eL8TYCAwxNJXv3T2FxjQHJspZCF968',
    appId: '1:749924368093:ios:cd1e5a213ccef18268a534',
    messagingSenderId: '749924368093',
    projectId: 'almalek-alameen-e205c',
    storageBucket: 'almalek-alameen-e205c.firebasestorage.app',
    iosBundleId: 'com.example.almalekAlameen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb_eL8TYCAwxNJXv3T2FxjQHJspZCF968',
    appId: '1:749924368093:ios:cd1e5a213ccef18268a534',
    messagingSenderId: '749924368093',
    projectId: 'almalek-alameen-e205c',
    storageBucket: 'almalek-alameen-e205c.firebasestorage.app',
    iosBundleId: 'com.example.almalekAlameen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUOs7vCJng2kFSyq5A58sdmFjLu69jg6s',
    appId: '1:749924368093:web:435c8010a12f193568a534',
    messagingSenderId: '749924368093',
    projectId: 'almalek-alameen-e205c',
    authDomain: 'almalek-alameen-e205c.firebaseapp.com',
    storageBucket: 'almalek-alameen-e205c.firebasestorage.app',
    measurementId: 'G-MPEMJ40VVE',
  );
}
